const USER_ROLE = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  DEVELOPER: "DEVELOPER",
  SUBMITTER: "SUBMITTER"
};

const PROJECT_STATUS = {
  PROPOSITION: "PROPOSITION",
  DEVELOPMENT: "DEVELOPMENT",
  PRODUCTION: "PRODUCTION",
  ABANDONED: "ABANDONED",
  ON_HOLD: "ON HOLD",
  CANCELED: "CANCELED"
};

const TICKET_TYPE = {
  NEED_HELP: "NEED HELP",
  BUG: "BUG",
  FEATURE_REQUEST: "FEATURE REQUEST",
  DETAIL: "DETAIL"
};

const TICKET_STATUS = {
  COMPLETED: "COMPLETED",
  IN_PROGRESS: "IN PROGRESS",
  ASSIGNED: "ASSIGNED",
  PENDING: "PENDING"
};

const TICKET_PRIORITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  UNKNOWN: "UNKNOWN"
};

module.exports = {
  USER_ROLE,
  PROJECT_STATUS,
  TICKET_TYPE,
  TICKET_STATUS,
  TICKET_PRIORITY
};
